data:
  # Path to clean data
  clean: data\train-clean-100
  # Path to labels
  labels: data\8000_30_50_100_50_max_lite.csv
  # Path to noises data
  noise: data\noise-16k
  #Path to segmental data stored with textgrid annotations
  enot_data:


model:
  # The id of the model from models.py from 0 to {MODELS_COUNT - 1}
  id: 2
  # The name of the model from models.py one of {NAMES}
  name:
  # The path or directory to model weights which will be loaded
  weights: C:\Users\ggyan\Projects\Voice Activity Detection\train_results\DGGD_64_48_32_16_8\2024-09-15\res_1

noise:
  # The size of the noise pool for audio augmentation
  pool: 100
  # The count of noises added on a single audio
  count: 2
  # The duration of added noises in seconds separated by f,t
  duration: [5, 10]
  # The signal-to-noise ratio for audio augmentation
  snr: 3

train:
  # The number of workers for data loading during training
  workers: 1
  # The size of the batch for simultaneous usage of samples during training
  batch: 6400

ROC:
  # The threshold for labeling the prediction 0 or 1
  thresholds: [0, 1, 20]
  # If not exists the plots of current training run will be saved in results folder
  no_plot: false
  # The level of detail of printing
  print: 2
